#!/bin/bash
#
# A NEWBIE script to help avoid typing multiple mount commands for a 
# chroot session
#
# - sv@suivue.net
#

mount_root() {
        echo "Current partition layout: "
        lsblk
        echo ""
        printf "Enter partition to mount (e.g. /dev/sdb2): "
        read fs
        printf "Enter directory to mount to (e.g. /mnt): "
        read mp
        #fs=$1
        #mp=$2
        mount $fs $mp
}

mount_efi() {
        # select menu does not work in sh; it is a bash/ksh feature
        PS3="Select an EFI partition: "
        select efipart in $(fdisk -l | grep 'EFI System' | awk '{print $1}')
        do
        	mount $efipart $mp/boot/efi
        	break
        done
}

mount_others() {
        # bind mount other essential partitions for chroot
        mount --bind /dev $mp/dev
        mount --bind /proc $mp/proc
        mount --bind /sys $mp/sys
        mount --bind /sys/firmware/efi/efivars $mp/sys/firmware/efi/efivars

        if [ -f "$mp/run/systemd/resolve/stub-resolv.conf" ]; then
                cat /etc/resolv.conf > $mp/run/systemd/resolve/stub-resolv.conf
        else
                cat /etc/resolv.conf > $mp/etc/resolv.conf
        fi
}

switch_root() {
        chroot $mp \
        bash -c 'export PS1="\[\033[0;32m\](chroot) \[\033[0m\\]\u@\w# ";\
        bash --norc'
}


unmount_all() {
        echo "Unmounting all chroot mounts..."
        sudo umount -R $mp
}

mount_root
mount_efi
mount_others
switch_root
unmount_all

